# files
sass:
  sass_dir: ./_sass

exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - _deprecated

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      category: "Others"

# Site info
url: http://bcds.design
title: BCDS

# # Google analytics
# analytics:
#   hostname: ricostacruz.com
#   id: "UA-20473929-1"
